"""flopkit: secure SDK for the Flop Network Technocore layer."""

from .config import TechnocoreConfig
from .delegation import DelegationError, DelegationManager
from .identity import (
    did_to_public_key,
    generate_identity,
    public_key_to_did,
    sign_bytes,
    verify_signature,
)
from .ledger import ContributionLedger
from .proofs import (
    create_contribution_proof,
    verify_contribution_proof,
    write_proof,
)
from .tclk import (
    FrameType,
    PaperRail,
    SettlementRail,
    TCLKContract,
    TCLKError,
    TCLKManager,
    TCLKState,
    TranscriptFoldResult,
    capability_token,
    deal_room_name,
    decode_frame,
    derive_contract_id,
    encode_frame,
    fold_transcript,
    generate_secret,
    hashlock_from_secret,
    parse_capability_token,
    state_pointer_path,
    validate_point_statement,
    verify_hashlock,
)
from .technocore import (
    DuplicateMessageError,
    NoteConflictError,
    RateLimitedError,
    TechnocoreClient,
    TechnocoreError,
)

__all__ = [
    "ContributionLedger",
    "DelegationError",
    "DelegationManager",
    "DuplicateMessageError",
    "FrameType",
    "NoteConflictError",
    "PaperRail",
    "RateLimitedError",
    "SettlementRail",
    "TCLKContract",
    "TCLKError",
    "TCLKManager",
    "TCLKState",
    "TechnocoreClient",
    "TechnocoreConfig",
    "TechnocoreError",
    "TranscriptFoldResult",
    "capability_token",
    "create_contribution_proof",
    "deal_room_name",
    "decode_frame",
    "derive_contract_id",
    "did_to_public_key",
    "encode_frame",
    "fold_transcript",
    "generate_identity",
    "generate_secret",
    "hashlock_from_secret",
    "parse_capability_token",
    "public_key_to_did",
    "sign_bytes",
    "state_pointer_path",
    "validate_point_statement",
    "verify_contribution_proof",
    "verify_hashlock",
    "verify_signature",
    "write_proof",
]
